.TH "logic/speech Directory Reference" 3 "Wed Apr 19 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/speech Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBprim_type\&.h\fP"
.br
.ti -1c
.RI "file \fBspeechdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBspeechdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBsphinxrecognizer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsphinxrecognizer\&.h\fP"
.br
.in -1c
