.TH "logic Directory Reference" 3 "Fri Feb 28 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmap\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlogic\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogic\&.h\fP"
.br
.ti -1c
.RI "file \fBmapwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmapwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBmovements\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmovements\&.h\fP"
.br
.ti -1c
.RI "file \fBnavdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnavdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBrobotinfodialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrobotinfodialog\&.h\fP"
.br
.ti -1c
.RI "file \fBsystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.in -1c
