.TH "AmurCore::CaptureState" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AmurCore::CaptureState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::mutex \fBmutex\fP"
.br
.ti -1c
.RI "std::atomic< bool > \fBstop\fP {false}"
.br
.ti -1c
.RI "Mat \fBlatest\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Mat AmurCore::CaptureState::latest"

.SS "std::mutex AmurCore::CaptureState::mutex"

.SS "std::atomic<bool> AmurCore::CaptureState::stop {false}"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
