.TH "amurcore.h" 3 "Sun Mar 19 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amurcore.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAmurCore\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_PICTURE\fP   '\&./data/images/no_picture\&.jpeg'"
.br
.ti -1c
.RI "#define \fBSOURCE_STREAM\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NO_PICTURE   '\&./data/images/no_picture\&.jpeg'"

.SS "#define SOURCE_STREAM   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
