.TH "anytype_s" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anytype_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prim_type\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "long \fBi\fP"
.br
.ti -1c
.RI "unsigned long \fBui\fP"
.br
.ti -1c
.RI "double \fBfl\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double anytype_s::fl"

.SS "long anytype_s::i"

.SS "void* anytype_s::ptr"

.SS "unsigned long anytype_s::ui"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
