.TH "camera/camcalibrate.h" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
camera/camcalibrate.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'camsettingsholder\&.h'\fP
.br
\fC#include 'calibrator\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamCalibrate\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOUNT_SKIP_FRAMES\fP   7"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COUNT_SKIP_FRAMES   7"

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
