.TH "network/connectdialog.cpp" 3 "Sun Nov 20 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/connectdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'connectdialog\&.h'\fP
.br
\fC#include 'ui_connectdialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
