.TH "joystick/getstatebyjoy.cpp" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/getstatebyjoy.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'getstatebyjoy\&.h'\fP
.br
\fC#include 'joystick_factory\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
