.TH "grpcClient" 3 "Wed Apr 19 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grpcClient
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgrpcClient\fP (std::shared_ptr< grpc::Channel > channel, AMUR::AmurSensors *\fBsensors\fP, AMUR::AmurControls *const \fBcontrols\fP)"
.br
.ti -1c
.RI "grpc::Status \fBDataExchange\fP ()"
.br
.ti -1c
.RI "grpc::Status \fBDataStreamExchange\fP ()"
.br
.ti -1c
.RI "void \fBstopStream\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< AMUR::ServerOnRobot::Stub > \fBstub_\fP"
.br
.ti -1c
.RI "std::shared_ptr< grpc::Channel > \fBclientChannel\fP"
.br
.ti -1c
.RI "AMUR::AmurSensors * \fBsensors\fP"
.br
.ti -1c
.RI "AMUR::AmurControls * \fBcontrols\fP"
.br
.ti -1c
.RI "bool \fBstoppedStream\fP = true"
.br
.ti -1c
.RI "std::mutex \fBmuClient\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "grpcClient::grpcClient (std::shared_ptr< grpc::Channel > channel, AMUR::AmurSensors * sensors, AMUR::AmurControls *const controls)"

.SH "Member Function Documentation"
.PP 
.SS "grpc::Status grpcClient::DataExchange ()"

.SS "grpc::Status grpcClient::DataStreamExchange ()"

.SS "void grpcClient::stopStream ()"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<grpc::Channel> grpcClient::clientChannel\fC [private]\fP"

.SS "AMUR::AmurControls* grpcClient::controls\fC [private]\fP"

.SS "std::mutex grpcClient::muClient\fC [private]\fP"

.SS "AMUR::AmurSensors* grpcClient::sensors\fC [private]\fP"

.SS "bool grpcClient::stoppedStream = true\fC [private]\fP"

.SS "std::unique_ptr<AMUR::ServerOnRobot::Stub> grpcClient::stub_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
