.TH "grpcServer" 3 "Fri Sep 16 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grpcServer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.PP
Inherits AMUR::ClientOnRobot::Service\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetProtosPointers\fP (AMUR::AmurControls *const \fBcontrols\fP, AMUR::AmurSensors *const \fBsensors\fP)"
.br
.ti -1c
.RI "int \fBcheckConn\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "grpc::Status \fBDataExchange\fP ([[maybe_unused]] grpc::ServerContext *context, const AMUR::AmurSensors *request, AMUR::AmurControls *reply) override"
.br
.ti -1c
.RI "grpc::Status \fBDataStreamExchange\fP ([[maybe_unused]] grpc::ServerContext *context, grpc::ServerReaderWriter< AMUR::AmurControls, AMUR::AmurSensors > *stream) override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "AMUR::AmurControls * \fBcontrols\fP"
.br
.ti -1c
.RI "AMUR::AmurSensors * \fBsensors\fP"
.br
.ti -1c
.RI "std::mutex \fBmuServer\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int grpcServer::checkConn ()"

.SS "grpc::Status grpcServer::DataExchange ([[maybe_unused] ] grpc::ServerContext * context, const AMUR::AmurSensors * request, AMUR::AmurControls * reply)\fC [override]\fP, \fC [private]\fP"

.SS "grpc::Status grpcServer::DataStreamExchange ([[maybe_unused] ] grpc::ServerContext * context, grpc::ServerReaderWriter< AMUR::AmurControls, AMUR::AmurSensors > * stream)\fC [override]\fP, \fC [private]\fP"

.SS "void grpcServer::setProtosPointers (AMUR::AmurControls *const controls, AMUR::AmurSensors *const sensors)"

.SH "Member Data Documentation"
.PP 
.SS "AMUR::AmurControls* grpcServer::controls\fC [private]\fP"

.SS "std::mutex grpcServer::muServer\fC [private]\fP"

.SS "AMUR::AmurSensors* grpcServer::sensors\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
