.TH "grpcClient" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grpcClient
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgrpcClient\fP (std::shared_ptr< grpc::Channel > channel, std::shared_ptr< Controls > controlsPtr, std::shared_ptr< Sensors > sensorsPtr, std::shared_ptr< map_service::GetMapResponse > mapPtr)"
.br
.ti -1c
.RI "grpc::Status \fBDataExchange\fP ()"
.br
.ti -1c
.RI "grpc::Status \fBDataStreamExchange\fP ()"
.br
.ti -1c
.RI "grpc::Status \fBMapStream\fP ()"
.br
.ti -1c
.RI "void \fBstopStream\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< ServerOnRobot::Stub > \fBstub_\fP"
.br
.ti -1c
.RI "std::shared_ptr< grpc::Channel > \fBclientChannel\fP"
.br
.ti -1c
.RI "std::shared_ptr< Controls > \fBcontrols\fP"
.br
.ti -1c
.RI "std::shared_ptr< Sensors > \fBsensors\fP"
.br
.ti -1c
.RI "std::shared_ptr< map_service::GetMapResponse > \fBmap\fP"
.br
.ti -1c
.RI "bool \fBstoppedStream\fP = true"
.br
.ti -1c
.RI "std::mutex \fBmuClient\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "grpcClient::grpcClient (std::shared_ptr< grpc::Channel > channel, std::shared_ptr< Controls > controlsPtr, std::shared_ptr< Sensors > sensorsPtr, std::shared_ptr< map_service::GetMapResponse > mapPtr)"

.SH "Member Function Documentation"
.PP 
.SS "grpc::Status grpcClient::DataExchange ()"

.SS "grpc::Status grpcClient::DataStreamExchange ()"

.SS "grpc::Status grpcClient::MapStream ()"

.SS "void grpcClient::stopStream ()"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<grpc::Channel> grpcClient::clientChannel\fC [private]\fP"

.SS "std::shared_ptr<Controls> grpcClient::controls\fC [private]\fP"

.SS "std::shared_ptr<map_service::GetMapResponse> grpcClient::map\fC [private]\fP"

.SS "std::mutex grpcClient::muClient\fC [private]\fP"

.SS "std::shared_ptr<Sensors> grpcClient::sensors\fC [private]\fP"

.SS "bool grpcClient::stoppedStream = true\fC [private]\fP"

.SS "std::unique_ptr<ServerOnRobot::Stub> grpcClient::stub_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
