.TH "joystick/joystickdialog.h" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/joystickdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include 'v_joystick_adapter\&.h'\fP
.br
\fC#include 'getstatebyjoy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJoystickDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
