.TH "joystick/joystickstateworker.h" 3 "Sat Sep 9 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/joystickstateworker.h
.SH SYNOPSIS
.br
.PP
\fC#include 'getstatebyjoy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJoystickStateWorker\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
