.TH "JoyState" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JoyState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <getstatebyjoy\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBjoyId\fP = \-1"
.br
.ti -1c
.RI "QVector< bool > \fBbuttonVector\fP"
.br
.ti -1c
.RI "int \fBjoystickXaxis\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickYaxis\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickZLTaxis\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickXrotation\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickYrotation\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickZRTaxis\fP = 0"
.br
.ti -1c
.RI "int \fBjoystickPOV0\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QVector<bool> JoyState::buttonVector"

.SS "int JoyState::joyId = \-1"

.SS "int JoyState::joystickPOV0 = 0"

.SS "int JoyState::joystickXaxis = 0"

.SS "int JoyState::joystickXrotation = 0"

.SS "int JoyState::joystickYaxis = 0"

.SS "int JoyState::joystickYrotation = 0"

.SS "int JoyState::joystickZLTaxis = 0"

.SS "int JoyState::joystickZRTaxis = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
