.TH "Joystick" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Joystick
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <joystick\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstopAll\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoystick\fP (const std::shared_ptr< \fBJoyState\fP > state)"
.br
.ti -1c
.RI "\fB~Joystick\fP ()"
.br
.ti -1c
.RI "void \fBaddThread\fP ()"
.br
.ti -1c
.RI "void \fBstopThreads\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBJoyState\fP > \fBjoyState\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Joystick::Joystick (const std::shared_ptr< \fBJoyState\fP > state)"

.SS "Joystick::~Joystick ()"

.SH "Member Function Documentation"
.PP 
.SS "void Joystick::addThread ()"

.SS "void Joystick::stopAll ()\fC [signal]\fP"

.SS "void Joystick::stopThreads ()"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBJoyState\fP> Joystick::joyState\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
