.TH "joystick/joystickstateworker.cpp" 3 "Sun Nov 20 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/joystickstateworker.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'joystickstateworker\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
