.TH "JSONWorker" 3 "Sun Nov 20 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONWorker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsonworker\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSONWorker\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "int \fBreadJSON\fP (QString filename, const QJsonObject &json)"
.br
.ti -1c
.RI "int \fBwriteJSON\fP (QString filename, QJsonObject &json) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JSONWorker::JSONWorker (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int JSONWorker::readJSON (QString filename, const QJsonObject & json)"

.SS "int JSONWorker::writeJSON (QString filename, QJsonObject & json) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
