.TH "logic/logic.h" 3 "Fri Sep 16 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/logic.h
.SH SYNOPSIS
.br
.PP
\fC#include 'opencv2/opencv\&.hpp'\fP
.br
\fC#include 'speech/speechdialog\&.h'\fP
.br
\fC#include 'movements\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
