.TH "logic/mapdialog.h" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/mapdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include 'mapwidget\&.h'\fP
.br
\fC#include 'network/protobuf/map\&.grpc\&.pb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMapDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
