.TH "MapWidget::ZoneOverlay" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapWidget::ZoneOverlay
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mapwidget\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBid\fP {0}"
.br
.ti -1c
.RI "std::uint32_t \fBtypeId\fP {0}"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "QVector< QPointF > \fBcontour\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QColor MapWidget::ZoneOverlay::color"

.SS "QVector<QPointF> MapWidget::ZoneOverlay::contour"

.SS "std::uint32_t MapWidget::ZoneOverlay::id {0}"

.SS "QString MapWidget::ZoneOverlay::name"

.SS "std::uint32_t MapWidget::ZoneOverlay::typeId {0}"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
