.TH "logic/mapwidget.cpp" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/mapwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mapwidget\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QWheelEvent>\fP
.br
\fC#include <QMouseEvent>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <QtMath>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
