.TH "logic/mapwidget.h" 3 "Fri Feb 28 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/mapwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPoseQuaternion\fP"
.br
.ti -1c
.RI "class \fBMapWidget\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator!=\fP (const \fBPoseQuaternion\fP &lhs, const \fBPoseQuaternion\fP &rhs)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (const \fBPoseQuaternion\fP &lhs, const \fBPoseQuaternion\fP &rhs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static bool operator!= (const \fBPoseQuaternion\fP & lhs, const \fBPoseQuaternion\fP & rhs)\fC [static]\fP"

.SS "static bool operator== (const \fBPoseQuaternion\fP & lhs, const \fBPoseQuaternion\fP & rhs)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
