.TH "md_CHANGELOG" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- 0\&.2\&.0 (2023-04-30) 

.SS "Feat"
.IP "\(bu" 2
\fB\fBNetworkController\fP\fP: Add finding robots by broadcast request
.IP "\(bu" 2
\fB\fBNetworkController\fP\fP: Added first arp message via JSON
.PP
.SS "Fix"
.IP "\(bu" 2
\fBCMakeLists\fP: Fix some problems with compiling SpeechProccessor
.IP "\(bu" 2
\fB\fBNetworkController\fP\fP: Removed forgotten include to nonexisted file
.IP "\(bu" 2
\fBAmurCore\&.pro\fP: Fix gRPC linking error & add commitizen config
.IP "\(bu" 2
\fB\fBCamCalibrate\fP\fP: Fixed waiting new frame with chessboard, changed to std::chrono lib
.IP "\(bu" 2
\fBJSONWorker\fP: Disable JSONWorker, for possible building
.PP
.SH "0\&.1 (2022-06-01)"
.PP

