.TH "md_README" 3 "Sat Sep 9 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- Amur Core 
This is application for communicate with robot on RPi base with \fCAmurClient\fP\&.
.SH "Requirements:"
.PP
1) Qt 5\&.12\&.2 + qmake 2) OpenCV 4\&.0\&.1 3) Protobuf 3\&.7\&.0 4) SDL 2\&.0 5) PocketSphinx+SphinxBase 5prealpha-2 6) qt5-speech 5\&.12\&.2-1
.SH "Sensors of robot:"
.PP
1) Camera - OV5647 2) Accelerometer & Gyroscope & Magnitometer - MPU-9250 3) Barometer - BMP-280 4) Encoders: left wheel, right wheel & hands 5) Gas sensor - MQ-7 6) Battery voltage
.SH "Controls of Robot:"
.PP
1) Camera servoX, servoY - MG90S 2) Motors: left wheel, right wheel & hand 
