.TH "logic/movements.h" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/movements.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./joystick/joystick\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMoveSettings\fP"
.br
.ti -1c
.RI "struct \fBMoveSettings::JoyBindings\fP"
.br
.ti -1c
.RI "class \fBBaseControlStrategy\fP"
.br
.ti -1c
.RI "class \fBDeadzoneBaseControlStrategy\fP"
.br
.ti -1c
.RI "class \fBManualControl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
