.TH "MoveSettings" 3 "Thu Apr 27 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveSettings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <movements\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBJoyBindings\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBMoveSettings::JoyBindings\fP \fBjoyBindings\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBMoveSettings::JoyBindings\fP MoveSettings::joyBindings"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
