.TH "Movements" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movements
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <movements\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMovements\fP (std::shared_ptr< \fBJoyState\fP > \fBjoyState\fP, std::shared_ptr< Controls > \fBcontrols\fP)"
.br
.ti -1c
.RI "int \fBupdate\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheckChangeRelayButton\fP (int buttonNumber)"
.br
.ti -1c
.RI "void \fBcheckChangeLightButton\fP (int buttonNumber)"
.br
.ti -1c
.RI "int \fBwheelProcess\fP (int xAxis, int yAxis)"
.br
.ti -1c
.RI "int \fBmoveCameraProcess\fP (int xAxis, int yAxis)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< Controls > \fBcontrols\fP"
.br
.ti -1c
.RI "\fBMoveSettings\fP \fBmoveSettings\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBJoyState\fP > \fBjoyState\fP"
.br
.ti -1c
.RI "\fBJoyState\fP \fBlastJoyState\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Movements::Movements (std::shared_ptr< \fBJoyState\fP > joyState, std::shared_ptr< Controls > controls)"

.SH "Member Function Documentation"
.PP 
.SS "void Movements::checkChangeLightButton (int buttonNumber)\fC [private]\fP"

.SS "void Movements::checkChangeRelayButton (int buttonNumber)\fC [private]\fP"

.SS "int Movements::moveCameraProcess (int xAxis, int yAxis)\fC [private]\fP"

.SS "int Movements::update ()"

.SS "int Movements::wheelProcess (int xAxis, int yAxis)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<Controls> Movements::controls\fC [private]\fP"

.SS "std::shared_ptr<\fBJoyState\fP> Movements::joyState\fC [private]\fP"

.SS "\fBJoyState\fP Movements::lastJoyState\fC [private]\fP"

.SS "\fBMoveSettings\fP Movements::moveSettings\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
