.TH "logic/navdialog.h" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/navdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QGroupBox>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QListWidget>\fP
.br
\fC#include 'mapwidget\&.h'\fP
.br
\fC#include 'network/protobuf/robot\&.pb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNavDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
