.TH "logic/navigation_adapter.h" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/navigation_adapter.h
.SH SYNOPSIS
.br
.PP
\fC#include <QPointF>\fP
.br
\fC#include 'network/protobuf/robot\&.pb\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNavigationAdapter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Navigation::Pose * \fBNavigationAdapter::fromPoint\fP (const QPointF &point, Navigation::Pose *pose)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
