.TH "network/networkfactory.h" 3 "Mon Jan 5 2026" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/networkfactory.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'server\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNetworkFactory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
