.TH "NetworkController" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <networkcontroller\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkController\fP (std::shared_ptr< Controls > controlsPtr, std::shared_ptr< Sensors > sensorsPtr, std::shared_ptr< map_service::GetMapResponse > mapPtr)"
.br
.ti -1c
.RI "\fB~NetworkController\fP ()"
.br
.ti -1c
.RI "int \fBrunClient\fP (std::string &server_address)"
.br
.ti -1c
.RI "int \fBrunServer\fP (std::string &address_mask)"
.br
.ti -1c
.RI "int \fBrunArpingService\fP (int arpPort, int gRPCPort, QString &arpHeader)"
.br
.ti -1c
.RI "QList< std::shared_ptr< \fBRobotEntry\fP > > \fBgetRobots\fP () const"
.br
.ti -1c
.RI "std::shared_ptr< \fBgrpcClient\fP > & \fBgetClientInstance\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBgrpcServer\fP > & \fBgetServerInstance\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< Controls > \fBcontrols\fP"
.br
.ti -1c
.RI "std::shared_ptr< Sensors > \fBsensors\fP"
.br
.ti -1c
.RI "std::shared_ptr< map_service::GetMapResponse > \fBmap\fP"
.br
.ti -1c
.RI "grpc::Status \fBclientStatus\fP"
.br
.ti -1c
.RI "grpc::ServerBuilder \fBbuilder\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBgrpcServer\fP > \fBserverPtr\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBgrpcClient\fP > \fBclientPtr\fP"
.br
.ti -1c
.RI "int \fBmessageNo\fP = 1"
.br
.ti -1c
.RI "QUdpSocket * \fBudpSocket\fP = nullptr"
.br
.ti -1c
.RI "QList< std::shared_ptr< \fBRobotEntry\fP > > \fBrobots\fP"
.br
.ti -1c
.RI "QMap< quint16, QUdpSocket * > \fBclientSockets\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NetworkController::NetworkController (std::shared_ptr< Controls > controlsPtr, std::shared_ptr< Sensors > sensorsPtr, std::shared_ptr< map_service::GetMapResponse > mapPtr)"

.SS "NetworkController::~NetworkController ()"

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr<\fBgrpcClient\fP>& NetworkController::getClientInstance ()\fC [inline]\fP"

.SS "QList< std::shared_ptr< \fBRobotEntry\fP > > NetworkController::getRobots () const"

.SS "std::shared_ptr<\fBgrpcServer\fP>& NetworkController::getServerInstance ()\fC [inline]\fP"

.SS "int NetworkController::runArpingService (int arpPort, int gRPCPort, QString & arpHeader)"

.SS "int NetworkController::runClient (std::string & server_address)"

.SS "int NetworkController::runServer (std::string & address_mask)"

.SH "Member Data Documentation"
.PP 
.SS "grpc::ServerBuilder NetworkController::builder\fC [private]\fP"

.SS "std::shared_ptr<\fBgrpcClient\fP> NetworkController::clientPtr\fC [private]\fP"

.SS "QMap<quint16, QUdpSocket*> NetworkController::clientSockets\fC [private]\fP"

.SS "grpc::Status NetworkController::clientStatus\fC [private]\fP"

.SS "std::shared_ptr<Controls> NetworkController::controls\fC [private]\fP"

.SS "std::shared_ptr<map_service::GetMapResponse> NetworkController::map\fC [private]\fP"

.SS "int NetworkController::messageNo = 1\fC [private]\fP"

.SS "QList< std::shared_ptr<\fBRobotEntry\fP> > NetworkController::robots\fC [private]\fP"

.SS "std::shared_ptr<Sensors> NetworkController::sensors\fC [private]\fP"

.SS "std::shared_ptr<\fBgrpcServer\fP> NetworkController::serverPtr\fC [private]\fP"

.SS "QUdpSocket* NetworkController::udpSocket = nullptr\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
