.TH "NetworkController" 3 "Sat Sep 9 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <networkcontroller\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkController\fP (AMUR::AmurControls *const \fBcontrols\fP, AMUR::AmurSensors *const \fBsensors\fP)"
.br
.ti -1c
.RI "\fB~NetworkController\fP ()"
.br
.ti -1c
.RI "int \fBrunClient\fP (std::string &server_address)"
.br
.ti -1c
.RI "int \fBrunServer\fP (std::string &address_mask)"
.br
.ti -1c
.RI "int \fBrunArpingService\fP (int \fBarpPort\fP, int gRPCPort)"
.br
.ti -1c
.RI "void \fBstartBroadcasting\fP ()"
.br
.ti -1c
.RI "void \fBstopBroadcasting\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "AMUR::AmurSensors * \fBsensors\fP"
.br
.ti -1c
.RI "AMUR::AmurControls * \fBcontrols\fP"
.br
.ti -1c
.RI "grpc::Status \fBclientStatus\fP"
.br
.ti -1c
.RI "grpc::ServerBuilder \fBbuilder\fP"
.br
.ti -1c
.RI "\fBgrpcServer\fP \fBservice\fP"
.br
.ti -1c
.RI "QTimer \fBtimer\fP"
.br
.ti -1c
.RI "int \fBmessageNo\fP = 1"
.br
.ti -1c
.RI "QUdpSocket * \fBudpSocket\fP = nullptr"
.br
.ti -1c
.RI "QList< \fBRobot\fP * > \fBrobots\fP"
.br
.ti -1c
.RI "QMap< quint16, QUdpSocket * > \fBclientSockets\fP"
.br
.ti -1c
.RI "int \fBarpPort\fP = 7776"
.br
.ti -1c
.RI "int \fBmsBroadcastDelay\fP = 1000"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NetworkController::NetworkController (AMUR::AmurControls *const controls, AMUR::AmurSensors *const sensors)"

.SS "NetworkController::~NetworkController ()"

.SH "Member Function Documentation"
.PP 
.SS "int NetworkController::runArpingService (int arpPort, int gRPCPort)"

.SS "int NetworkController::runClient (std::string & server_address)"

.SS "int NetworkController::runServer (std::string & address_mask)"

.SS "void NetworkController::startBroadcasting ()"

.SS "void NetworkController::stopBroadcasting ()"

.SH "Member Data Documentation"
.PP 
.SS "int NetworkController::arpPort = 7776\fC [private]\fP"

.SS "grpc::ServerBuilder NetworkController::builder\fC [private]\fP"

.SS "QMap<quint16, QUdpSocket*> NetworkController::clientSockets\fC [private]\fP"

.SS "grpc::Status NetworkController::clientStatus\fC [private]\fP"

.SS "AMUR::AmurControls* NetworkController::controls\fC [private]\fP"

.SS "int NetworkController::messageNo = 1\fC [private]\fP"

.SS "int NetworkController::msBroadcastDelay = 1000\fC [private]\fP"

.SS "QList<\fBRobot\fP*> NetworkController::robots\fC [private]\fP"

.SS "AMUR::AmurSensors* NetworkController::sensors\fC [private]\fP"

.SS "\fBgrpcServer\fP NetworkController::service\fC [private]\fP"

.SS "QTimer NetworkController::timer\fC [private]\fP"

.SS "QUdpSocket* NetworkController::udpSocket = nullptr\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
