.TH "network/networkcontroller.h" 3 "Sat Feb 1 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/networkcontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QtNetwork>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include 'robotentry\&.h'\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'server\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNetworkController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
