.TH "RobotInfoDialog" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RobotInfoDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robotinfodialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRobotInfoDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~RobotInfoDialog\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButton_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::RobotInfoDialog * \fBui\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RobotInfoDialog::RobotInfoDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "RobotInfoDialog::~RobotInfoDialog ()"

.SH "Member Function Documentation"
.PP 
.SS "void RobotInfoDialog::on_pushButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Ui::RobotInfoDialog* RobotInfoDialog::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
