.TH "logic/robotinfodialog.cpp" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/robotinfodialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'robotinfodialog\&.h'\fP
.br
\fC#include 'ui_robotinfodialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
