.TH "network/robotentry.h" 3 "Fri Feb 28 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/robotentry.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QtNetwork>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRobotEntry\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBRobotEntryPtr\fP = std::shared_ptr< \fBRobotEntry\fP >"
.br
.ti -1c
.RI "using \fBRobotList\fP = QList< \fBRobotEntryPtr\fP >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBRobotEntryPtr\fP =  std::shared_ptr<\fBRobotEntry\fP>"

.SS "using \fBRobotList\fP =  QList<\fBRobotEntryPtr\fP>"

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
