.TH "network/server.h" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/server.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <grpcpp/grpcpp\&.h>\fP
.br
\fC#include <grpcpp/health_check_service_interface\&.h>\fP
.br
\fC#include <grpcpp/ext/proto_server_reflection_plugin\&.h>\fP
.br
\fC#include 'network/protobuf/robot\&.grpc\&.pb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgrpcServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
