.TH "Session" 3 "Wed Apr 19 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Session
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <session\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstopAll\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSession\fP ()"
.br
.ti -1c
.RI "\fB~Session\fP ()"
.br
.ti -1c
.RI "void \fBaddThread\fP ()"
.br
.ti -1c
.RI "void \fBstopThreads\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Session::Session ()"

.SS "Session::~Session ()"

.SH "Member Function Documentation"
.PP 
.SS "void Session::addThread ()"

.SS "void Session::stopAll ()\fC [signal]\fP"

.SS "void Session::stopThreads ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
