.TH "logic/speech/speechdialog.cpp" 3 "Wed Jan 8 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/speech/speechdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'speechdialog\&.h'\fP
.br
\fC#include 'ui_speechdialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
