.TH "logic/speech/speechdialog.h" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/speech/speechdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QTextToSpeech>\fP
.br
\fC#include <QLoggingCategory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpeechDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
