.TH "logic/speech/sphinxrecognizer.h" 3 "Thu Apr 27 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/speech/sphinxrecognizer.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSphinxRecognizer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
