.TH "SphinxRecognizer" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SphinxRecognizer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sphinxrecognizer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSphinxRecognizer\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SphinxRecognizer::SphinxRecognizer ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
