.TH "joystick/v_joystick_adapter.h" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/v_joystick_adapter.h
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_joystick\&.h>\fP
.br
\fC#include <SDL2/SDL_haptic\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVJoystickAdapter\fP"
.br
.ti -1c
.RI "class \fBVJoystickAdapter::VJoystickThread\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
