.TH "joystick/v_joystick_adapter.cpp" 3 "Wed Apr 9 2025" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick/v_joystick_adapter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'v_joystick_adapter\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
