.TH "VJoystickAdapter::VJoystickThread" 3 "Sun Apr 30 2023" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VJoystickAdapter::VJoystickThread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <v_joystick_adapter\&.h>\fP
.PP
Inherits QThread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVJoystickThread\fP (\fBVJoystickAdapter\fP *adapter)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBVJoystickAdapter\fP * \fBm_adapter\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VJoystickAdapter::VJoystickThread::VJoystickThread (\fBVJoystickAdapter\fP * adapter)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void VJoystickAdapter::VJoystickThread::run ()\fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVJoystickAdapter\fP* VJoystickAdapter::VJoystickThread::m_adapter\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
