.TH "Worker" 3 "Tue May 31 2022" "Version 1.0" "AmurCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Worker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <worker\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBprocess\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBfinished\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorker\fP ()"
.br
.ti -1c
.RI "\fB~Worker\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Worker::Worker ()"

.SS "Worker::~Worker ()"

.SH "Member Function Documentation"
.PP 
.SS "void Worker::finished ()\fC [signal]\fP"

.SS "void Worker::process ()\fC [slot]\fP"

.SS "void Worker::stop ()\fC [slot]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurCore from the source code\&.
